#!/bin/bash

set -e
set -u

ip=$1

if [ -z "$ip" ]
then
	echo "Usage: $0 ip"
	exit 1
fi


whoisfile=/tmp/add-ip-whois
whois=$(whois $ip > $whoisfile)
if [ $? -ne 0 ]
then
	echo "Unable to get informations from whois for $ip"
	exit 1
fi

if [ -n "$(cat $whoisfile | grep -i 'no match')" ]
then
	echo "No match for $ip"
	echo $ip/32 >> lists/divers.txt
	exit 0
fi

inetnum=$(cat $whoisfile | grep -i inetnum: | head -n 1 | cut -d':' -f 2-)
if [ -z "$inetnum" ]
then
	inetnum=$(cat $whoisfile | grep -i netrange: | head -n 1 | cut -d':' -f 2-)
fi

if [ -z "$inetnum" ]
then
	inetnum=$(cat $whoisfile | grep -i '\[Network Number\]' | head -n 1 | cut -d ']' -f 2-)
fi

netname=$(cat $whoisfile | grep -i netname: | head -n 1 | cut -d':' -f 2- | awk '{print $1; }')
if [ -z "$netname" ]
then
	netname=$(cat $whoisfile | grep -i aut-name | head -n 1 | cut -d':' -f 2- | awk '{ print $1; }')
fi

if [ -z "$netname" ]
then
	netname=$(cat $whoisfile | grep -i '\[Network Name\]' | head -n 1 | cut -d ']' -f 2-)
fi

if [ -z "$netname" ]
then
	netname="divers"
fi

## bash trim
netname=$(echo $netname)
inetnum=$(echo $inetnum)

isCidr=$(echo $inetnum | grep '/' || true)
if [ ! -z "$isCidr" ]
then
	range=$inetnum
else
	range=$(ipcalc $inetnum | grep -v deaggregate)
	if [ $? -ne 0 ]
	then
		echo "And error occured while treating range '$inetnum'."
		echo "It returned :"
		echo $range
		exit 1
	fi
	if [ -n "$(echo $range | grep Usage)" ]
	then
		echo "And error occured while treating range '$inetnum'."
		echo "It returned :"
		echo $range
		echo $ip/32 >> lists/divers.txt
		exit 1
	fi
fi

isInvalid=$(echo $range | grep 'INVALID ADDRESS' || true)
if [ ! -z "$isInvalid" ]
then
	#echo "And error occured while treating range '$inetnum'."
	#echo "It returned :"
	#echo $range
	#exit 1
	inetname=$(cat $whoisfile | grep -i aut-num | head -n 1 | cut -d':' -f 2- | awk '{ print $1; }')
	nbDigit=$(echo $inetnum | cut -d/ -f 1 | tr '.' ' ' | wc -w)
	ipRange=$(echo $inetnum | cut -d/ -f 1)
	netmask=$(echo $inetnum | cut -d/ -f 2)
	case $nbDigit in
		4)
			echo "An error occured, $inetnum seems a good range :("
			exit 1
			;;

		3)
			range="$ipRange.0/$netmask"
			;;

		2)
			range="$ipRange.0.0/$netmask"
			;;
		1)
			echo "Warning, missing 3 digits in ip '$inetnum' !"
			range="$ipRange.0.0.0/$netmask"
			;;
		*)
			echo "An error occured while treating ip '$inetnum'"
			exit 1
			;;
	esac
fi


#echo "intenum: $inetnum"
#echo "netname: $netname"
#echo "range: $range"

for r in $range
do
	echo $r >> lists/$netname.txt
done

rm $whoisfile
exit 0

